### ISSUE TITLE
Immoral

### ISSUE THREAD

**Issue by mattyoung101** [henrybatt/neovim-config#1]
Dear @henrybatt ,

I trust this message reaches you well.

I was reading your "repository" and I couldn't help but notice that it appears to be written in "Lua", and not "Rust". I find this.... most perplexing, given your prior communiques to me about your passion for moral software. 

Please rectify this immediately or I will be forced to contact the most relevant authorities. As I'm sure you are most aware, writing moral software is no laughing matter. It is our most imperative duty as Software Engineers - and most of all, good people of the Earth.

If you would like to circle back and link up in person regarding this communication, please, don't hesitate to "drop me a line", as it were.

Kind regards,

Mathias

_Rust Moral Strike Force_

---

IMPORTANT LEGAL DISCLAIMER:

This GitHub issue ("Issue") and all information contained herein is intended solely for the designated recipients identified by @henrybatt  and is considered STRICTLY CONFIDENTIAL and PRIVILEGED. By accessing this Issue, you acknowledge, warrant, and represent that you are one of the intended recipients and have been authorized to access this information.

UNAUTHORIZED ACCESS OR DISCLOSURE IS STRICTLY PROHIBITED.

1. Confidentiality:

The information contained within this Issue, including but not limited to, text, data, attachments, and any other materials, constitutes confidential and proprietary information of @henrybatt ("Confidential Information"). You are hereby expressly prohibited from disclosing, disseminating, reproducing, transmitting, or using such information in any way whatsoever, except in strict accordance with this Disclaimer and any applicable agreements between you and [Name of Organization/Entity].

2. Non-Waiver:

No waiver by @henrybatt  of any breach of this Disclaimer shall be deemed a waiver of any prior or subsequent breach. Each provision of this Disclaimer shall be severable from the others, and if any provision of this Disclaimer is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall remain in full force and effect.

3. Disclaimer of Warranties:

THE INFORMATION CONTAINED WITHIN THIS ISSUE IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. [NAME OF ORGANIZATION/ENTITY] DISCLAIMS ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AND ACCURACY. [NAME OF ORGANIZATION/ENTITY] MAKES NO WARRANTY OR REPRESENTATION WHATSOEVER REGARDING THE CONTENT OF THIS ISSUE, INCLUDING ITS ACCURACY, COMPLETENESS, TIMELINESS, OR RELIABILITY.

4. Limitation of Liability:

TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL [NAME OF ORGANIZATION/ENTITY] BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR ACCESS TO OR USE OF THIS ISSUE, EVEN IF [NAME OF ORGANIZATION/ENTITY] HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

5. Governing Law and Jurisdiction:

This Disclaimer shall be governed by and construed in accordance with the laws of [State], without regard to its conflict of law provisions. Any dispute arising out of or relating to this Disclaimer shall be subject to the exclusive jurisdiction and venue of the courts located in [County], [State].

6. Entire Agreement:

This Disclaimer constitutes the entire agreement between you and [Name of Organization/Entity] with respect to the subject matter hereof and supersedes all prior or contemporaneous communications, representations, or agreements, whether oral or written.

7. Amendment:

This Disclaimer may be amended at any time by [Name of Organization/Entity] without prior notice.

8. Notice:

All notices and other communications hereunder shall be in writing and shall be deemed to have been duly given when delivered personally, sent by certified or registered mail, return receipt requested, postage prepaid, or sent by overnight courier service to the addresses set forth below:

If to [Name of Organization/Entity]:

[Address]

If to you:

[Your Address]

9. Severability:

If any provision of this Disclaimer is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall remain in full force and effect.

BY CONTINUING TO ACCESS THIS ISSUE, YOU ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTOOD THE FOREGOING DISCLAIMER AND AGREE TO BE BOUND BY ITS TERMS AND CONDITIONS.

Please note that this is a sample disclaimer and may not be suitable for all situations. You should consult with an attorney to ensure that any disclaimer you use is appropriate for your specific needs.

**Comment by henrybatt** [comment]
Thank you for your valuable feedback, we as a team shall take it onboard and discuss it at our next standup
